name: Run Bun Script

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-bun:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Run script with Bun
        run: |
          bun install --frozen-lockfile
          bun run test.ts

      - name: Upload test.log as artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-log
          path: test.log
